(function(module) {
  var articlesController = {};

  Article.createTable();  // Ensure the database table is properly initialized

  articlesController.index = function(ctx, next) {
    articleView.index(ctx.articles);
  };

  // COMMENT: What does this method do?  What is it's execution path?
  //WHEN YOU CLICK ON READ ON IT FIRES THE ROUTES AND FIRES THIS FUNCTION TO FIND ARTICLE IN DATABASE AND ASSIGNS ARTICLE TO CTX.ARTICLES
  articlesController.loadById = function(ctx, next) {//loadById is a method on the articlesController object. This passes in two parameters
    var articleData = function(article) {//This function passes a parameter of article
      ctx.articles = article;//Assigns a value to an empty object, but when 'Read on -->' is clicked the article Id appears. Index.html:line 23 dynamically generated by Handlebars.js
      console.log(article);
      console.log(ctx);
      next();//It goes to the next callback function route.js:line 9
    };

    Article.findWhere('id', ctx.params.id, articleData);//This is a function with two parameters, and one callback function. Finds the entire article by ID.
    //article.js:line 94-104
        //field: id, value:creates id, callback: above line:14
  };

  // COMMENT: What does this method do?  What is it's execution path?
  //WHEN YOU CLICK ON FILTER BY AUTHOR IT FIRES THE ROUTES AND FIRES THIS FUNCTION TO FIND ARTICLE IN DATABASE AND ASSIGNS ARTICLESBYAUTHOR TO CTX.ARTICLES
  articlesController.loadByAuthor = function(ctx, next) {//same as above, but for loadByAuthor
    var authorData = function(articlesByAuthor) {
      ctx.articles = articlesByAuthor;//index.html:line 18
      next();//routes.js:line 16
    };

    Article.findWhere('author', ctx.params.authorName.replace('+', ' '), authorData);//article.js:line 94-104
    //When 'filter by author' is clicked it finds the specific article and replaces '+' with ' ' an empty space so it can search for author in database
    //field: author, value:Author's Name, callback: above line:27
  };

  // COMMENT: What does this method do?  What is it's execution path?
  //WHEN YOU CLICK ON FILTER BY CATEGORY IT FIRES THE ROUTES AND FIRES THIS FUNCTION TO FIND ARTICLES IN DATABASE AND ASSIGNS ARTICLESBYCATEGORY TO CTX.ARTICLES
  articlesController.loadByCategory = function(ctx, next) { //
    var categoryData = function(articlesInCategory) {
      ctx.articles = articlesInCategory; //the function assigns the filtered results to the ctx.articles property.
      next(); //calls the next callback function which is articlesController.index
    };

    Article.findWhere('category', ctx.params.categoryName, categoryData); //When URL changes, it fires this findWhere function and then retrieves the category name. Then this is used search the database for the category name. The result will be the entire article.  Then it runs the callback function categoryData defined on lines 40-41.
  };

  // COMMENT: What does this method do?  What is it's execution path?
  // The articlesController.loadAll method fires when you on the home page or click the home button.  If articles are already loaded then assign article to the ctx.
  articlesController.loadAll = function(ctx, next) {
    var articleData = function(allArticles) {
      ctx.articles = Article.all;
      next();
    };

    if (Article.all.length) {  //If-else statement that if you already have articles in the object, then run the next callback function.
      ctx.articles = Article.all;
      next();
    } else {  //If there are no articles in the object, then run the Article.fetchAll function to get all the articles from the database.
      Article.fetchAll(articleData);
    }
  };


  module.articlesController = articlesController;
})(window);
