(function(module) {
  var articlesController = {};

  Article.createTable();  // Ensure the database table is properly initialized

  articlesController.index = function(ctx, next) {
    articleView.index(ctx.articles);
  };

  // COMMENT: What does this method do?  What is it's execution path?
  //WHEN YOU CLICK ON READ ON IT FIRES THE ROUTES AND FIRES THIS FUNCTION TO FIND ARTICLE IN DATABASE AND ASSIGNS ARTICLE TO CTX.ARTICLES
  articlesController.loadById = function(ctx, next) {//loadById is a method on the articlesController object. This passes in two parameters
    var articleData = function(article) {//This function passes a parameter of article
      ctx.articles = article;//Assigns a value to an empty object, but when 'Read on -->' is clicked the article Id appears. Index.html:line 23 dynamically generated by Handlebars.js
      console.log(article);
      console.log(ctx);
      next();//It goes to the next callback function route.js:line 9
    };

    Article.findWhere('id', ctx.params.id, articleData);//This is a function with two parameters, and one callback function. Finds the entire article by ID.
    //article.js:line 94-104
        //field: id, value:creates id, callback: above line:14
  };

  // COMMENT: What does this method do?  What is it's execution path?
  //WHEN YOU CLICK ON FILTER BY AUTHOR IT FIRES THE ROUTES AND FIRES THIS FUNCTION TO FIND ARTICLE IN DATABASE AND ASSIGNS ARTICLESBYAUTHOR TO CTX.ARTICLES
  articlesController.loadByAuthor = function(ctx, next) {//same as above, but for loadByAuthor
    var authorData = function(articlesByAuthor) {
      ctx.articles = articlesByAuthor;//index.html:line 18
      next();//routes.js:line 16
    };

    Article.findWhere('author', ctx.params.authorName.replace('+', ' '), authorData);//article.js:line 94-104
    //When 'filter by author' is clicked it finds the specific article and replaces '+' with ' ' an empty space so it can search for author in database
    //field: author, value:Author's Name, callback: above line:27
  };

  // COMMENT: What does this method do?  What is it's execution path?
  articlesController.loadByCategory = function(ctx, next) {
    var categoryData = function(articlesInCategory) {
      ctx.articles = articlesInCategory;
      next();
    };

    Article.findWhere('category', ctx.params.categoryName, categoryData);
  };

  // COMMENT: What does this method do?  What is it's execution path?
  articlesController.loadAll = function(ctx, next) {
    var articleData = function(allArticles) {
      ctx.articles = Article.all;
      next();
    };

    if (Article.all.length) {
      ctx.articles = Article.all;
      next();
    } else {
      Article.fetchAll(articleData);
    }
  };


  module.articlesController = articlesController;
})(window);
